### ISSUE TITLE
Getting gas error when trying to bridge back from L2 to L1.

### ISSUE THREAD

**Issue by cryptoxman** [bobanetwork/boba_legacy#675] opened 2023-03-22 20:22 UTC
"cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: ERC20: transfer amount exceeds allowance", method="estimateGas"

Was set to Gas limit of 53013 and 1 gwei

![Image](https://user-images.githubusercontent.com/30192212/227028658-52117059-3aff-4615-b4a0-924b9daf78ee.png)

**Comment by wsdt** [comment] 2023-05-03 10:22
bridging back itself works, looks like we just use the approved or max amount to bridge back instead of what the user actually selects on the frontend, example: 
https://testnet.bobascan.com/tx/0x7123fe3189b5da66f37a4aa1836baeeebc55c6d923f1f001221426e39ee8b5d0

Looks like it bridged 10 BOBA, although I selected 0.02 ETH: 
![image](https://user-images.githubusercontent.com/28724551/235891212-4c468c55-f180-42f6-8b80-24517b82ab32.png)


Will have a look

**Comment by wsdt** [comment] 2023-05-03 10:49
@cryptoxman what are the steps to reproduce this? 

was able to withdraw back 0.2 ETH with 10 BOBA for relaying the message. 
https://testnet.bobascan.com/tx/0x7123fe3189b5da66f37a4aa1836baeeebc55c6d923f1f001221426e39ee8b5d0

**Comment by wsdt** [comment] 2023-05-05 12:48
Another try, with explicitly using 10 BOBA approval instead of max as I did before - still works: 
https://testnet.bobascan.com/tx/0x6d82c713d4b314bcc1b0ab9f0c330faf53f07d7b3cf4fbe693d83b4472291898

As per messaging with Ocean and the error message above it could be that simply not enough Boba tokens were approved by the user (user error). 

Alternatively we may consider improving the user experience and separating the `approving` step from the actual bridging transaction.

**Comment by wsdt** [comment] 2023-05-05 12:49
Closing this issue for now, if you think this issue should be still active feel free to reopen @cryptoxman

**Closed as completed by wsdt** 2023-05-05 12:49 UTC
Labels: gateway

**Comment by wsdt** [comment] 2023-05-09 17:40
Seemingly just pops up randomly according to Ocean, but couldn't reproduce that either yet.
