### ISSUE TITLE
Pop up for the network authorization switch

### ISSUE THREAD

**Issue by cschlauf** [bobanetwork/boba_legacy#644] opened 2023-03-08 18:50 UTC

**Comment by cschlauf** [comment] 2023-03-08 18:51
![Image](https://user-images.githubusercontent.com/121965721/223807371-6148b06d-1726-4178-a283-1016ad96b9ba.png)

Rather than having to click in the top right hand corner - which some users may not do enable a pop up in the middle of the screen if there is not an auto switch.

**Comment by sk-enya** [comment] 2023-03-09 19:09
@cschlauf can you please more details on this how we can reproduce this issue?

You mean we should disable the popup on browser then try connecting to MM?

**Comment by cschlauf** [comment] 2023-03-10 04:04
Made a loom explaining for you https://www.loom.com/share/e72a3e8c211046baa8a41cbf3d20fc54

**Comment by boyuan-chen** [comment] 2023-03-11 00:11
It's impossible to switch automatically without asking the permission from users. 

> The potential critical issue of automatically switching is the `replay attacks`. 

What we can do is to automatically pop up the window and ask users to confirm it.

**Comment by cschlauf** [comment] 2023-03-13 01:41
that works - just as long as it's middle of the screen. Rather than having them figure out that they have to confirm.

**Comment by wsdt** [comment] 2023-03-13 12:20
@sk-enya @cschlauf So are we good to implement this?
Shall we basically just have a centered (blocking) switch network modal automatically popping up when the user is on the wrong network?

**Comment by cschlauf** [comment] 2023-03-14 03:57
yup - feel free to take creative liberties here. Just want it to be obvious to someone that they are on the wrong network. There were instances where I was on the wrong network and didn't know it. Had there been a clear pop up or display that told me I was it would have saved me some time and a headache.

**Comment by sk-enya** [comment] 2023-03-14 05:09
@cschlauf yup, this is good suggestion, actually we were referring to safe-gnosis for implementing the multi chain so the reason we have added the button `Switch to BNB network` whenever user want to switch to another network.

Okay, we will add centered blocking switch network modal to have better user experience, as soon as [PR625](https://github.com/bobanetwork/boba/pull/625) get merged.

**Closed as completed** 2023-03-16 21:40 UTC
